name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci:
    name: CI (stable)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Test with default feature
        run: cargo test

      - name: Test with tokio feature
        run: cargo test --features tokio_socket

      - name: Test with smol_socket feature
        run: cargo test --features smol_socket
