name: Minium Support Rust Version Test

concurrency:
  group: msrv-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
   types: [opened, synchronize, reopened]
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  build_on_msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build test
        run: cargo build --ignore-rust-version
